version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_biblioteca
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./biblioteca
    container_name: backend_biblioteca
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/biblioteca
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: clave

  frontend:
    build:
      context: ./biblioteca_front
    container_name: frontend_biblioteca
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
